# Copyright (c) 2025 Robert Schiwon
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

lib-js:build:
  image: rust:1.85
  stage: build
  script:
    - cd lib-js
    - rustup target add wasm32-unknown-unknown
    - cargo install wasm-pack --quiet
    - wasm-pack build --dev
  artifacts:
    paths:
      - lib-js/pkg

lib-js:format:
  image: rust:1.85
  stage: test
  script:
    - cd lib-js
    - rustup component add rustfmt
    - cargo fmt --check

lib-js:lint:
  image: rust:1.85
  stage: test
  script:
    - cd lib-js
    - rustup component add clippy
    - cargo clippy

# todo: update image for running tests in
# see: https://github.com/rustwasm/wasm-pack/issues/1355
# lib-js:test:
#   image: rust:1.85
#   stage: test
#   script:
#     - cd lib-js
#     - rustup target add wasm32-unknown-unknown
#     - cargo install wasm-pack --quiet
#     - wasm-pack test --chrome --headless

lib-js:outdated:
  image: rust:1.85
  stage: test
  script:
    - cd lib-js
    - ./check_updates.sh
  allow_failure: true

lib-js:release:
  image: rust:1.85
  stage: release
  script:
    - cd lib-js
    - rustup target add wasm32-unknown-unknown
    - cargo install wasm-pack --quiet
    - wasm-pack build --release
  artifacts:
    paths:
      - lib-js/pkg
  only:
    - main
