lib-rs:build:
  image: rust:1.84
  stage: build
  script:
    - cd lib-rs
    - cargo build
  artifacts:
    paths:
      - lib-rs/target/debug

lib-rs:format:
  image: rust:1.84
  stage: test
  script:
    - cd lib-rs
    - rustup component add rustfmt
    - cargo fmt --check

lib-rs:lint:
  image: rust:1.84
  stage: test
  script:
    - cd lib-rs
    - rustup component add clippy
    - cargo clippy

lib-rs:test:
  image: rust:1.84
  stage: test
  script:
    - cd lib-rs
    - cargo test

lib-rs:outdated:
  image: rust:1.84
  stage: test
  script:
    - cd lib-rs
    - ./check_updates.sh
  allow_failure: true

lib-rs:coverage:
  image: rust:1.84
  stage: test
  script:
    - cd lib-rs
    - apt-get -y update && apt-get -y install lcov
    - rustup component add llvm-tools-preview
    - cargo install grcov --quiet
    - ./coverage.sh
  artifacts:
    paths:
      - lib-rs/target/debug/coverage

lib-rs:release:
  image: rust:1.84
  stage: release
  script:
    - cd lib-rs
    - cargo build --release
  artifacts:
    paths:
      - lib-rs/target/release
  only:
    - main

# pages:
#   stage: publish
#   script:
#     - rm -rf public
#     - mkdir public
#     - mv target/debug/coverage public/coverage
#   dependencies:
#     - coverage
#   artifacts:
#     paths:
#       - lib-rs/public
#   only:
#     - master
