image: rust:1.74

before_script:
  - cd lib-rs

stages:
  - test
  - coverage
  - build
  - doc
  - publish

format:
  stage: test
  script:
    - rustup component add rustfmt
    - cargo fmt --check

lint:
  stage: test
  script:
    - rustup component add clippy
    - cargo clippy

test:
  stage: test
  script:
    - cargo test

coverage:
  stage: test
  script:
    - rustup component add llvm-tools-preview
    - cargo install grcov --quiet
    - ./coverage.sh
  artifacts:
    paths:
      - lib-rs/target/debug/coverage

build:
  stage: build
  script:
    - cargo build --release
  artifacts:
    paths:
      - lib-rs/target/release

build:wasm:
  stage: build
  script:
    - rustup target add wasm32-unknown-unknown
    - cargo install wasm-pack --quiet
    - wasm-pack build
  artifacts:
    paths:
      - lib-rs/pkg

# pages:
#   stage: publish
#   script:
#     - rm -rf public
#     - mkdir public
#     - mv target/debug/coverage public/coverage
#   dependencies:
#     - coverage
#   artifacts:
#     paths:
#       - lib-rs/public
#   only:
#     - master
