image: node:20

cache:
  paths:
    - node_modules/

before_script:
  - npm install
  - cd web-ui

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - CI=true npm test -- --coverage
  # coverage: /All files\s*\|\s*([\d\.]+)/

audit:
  stage: test
  script:
    - npm audit --audit-level=critical --production
  allow_failure: true

outdated:
  stage: test
  script:
    - npm outdated
  allow_failure: true

build:
  stage: build
  script:
    - CI=true npm run build
  artifacts:
    paths:
      - web-ui/dist
  only:
    - main

# pages:
#   stage: deploy
#   script:
#     - rm -rf public
#     - mv dist public
#     - gzip -k -r -6 public
#   artifacts:
#     paths:
#       - public
#   only:
#     - main
