image: node:20

cache:
  paths:
    - node_modules/

before_script:
  - cd web-ui
  - npm install

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - CI=true npm test -- --coverage
  # coverage: /All files\s*\|\s*([\d\.]+)/
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: lib-cpp
    - pipeline: $PARENT_PIPELINE_ID
      job: lib-rs

audit:
  stage: test
  script:
    - npm audit --audit-level=critical --production
  allow_failure: true

outdated:
  stage: test
  script:
    - npm outdated
  allow_failure: true

build:
  stage: build
  script:
    - npm run import-wasm
    - CI=true npm run build
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: lib-cpp
    - pipeline: $PARENT_PIPELINE_ID
      job: lib-rs
  artifacts:
    paths:
      - web-ui/dist
  only:
    - main

pages:
  stage: deploy
  script:
    - rm -rf public
    - mv dist public
    - gzip -k -r -6 public
  artifacts:
    paths:
      - public
  only:
    - main
