name: CD Web

on:
  workflow_dispatch:
    # inputs:
    #   environment:
    #     type: choice
    #     description: Into what environment to deploy.
    #     options: 
    #       - dev
    #       - qa
    #       - prod
  workflow_call:

defaults:
  run:
    working-directory: ./web-ui

jobs:
  publish_web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Noop
        run: |
          echo "publish called"
          ls -la ..
