name: CI JavaScript

# on:
#   push:
#     # branches: ['main']
#   pull_request:
#     # branches: ['main']
on:
  workflow_dispatch:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: ./lib-js

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: Temporarily modify the rust toolchain version
      #   run: rustup override set nightly
      - uses: actions/checkout@v5
      - name: Rust version
        run: rustup --version
      - name: Install dependencies
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install wasm-pack --quiet
      - name: Build
        run: wasm-pack build --dev

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Format
        run: cargo fmt --check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Lint
        run: cargo clippy

  outdated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Outdated
        run: ./check_updates.sh

  test:
    runs-on: ubuntu-latest
    needs: [build, format, lint, outdated]
    steps:
      - uses: actions/checkout@v5
      - name: Install dependencies
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install wasm-pack --quiet
      - name: Build
        run: wasm-pack test --chrome --headless
    
  # publish:
  #   needs: [test]
  #   permissions: read-all
  #   # if: github.refs == 'refs/heads/main'
  #   # if: startsWith(github.event.ref, 'refs/tags/v')
  #   uses: './.github/workflows/cd-js.yml'
  #   # with:
  #   #   environment: prod
