name: CI Web

# on:
#   workflow_run:
#     workflows: [CI JavaScript]
#     types: [completed]
# on:
#   push:
#     # branches: ['main']
#   pull_request:
#     # branches: ['main']
on:
  workflow_dispatch:
    inputs:
      runid:
        type: string
        required: true
        description: The run ID of the workflow that uploaded the wasm-webpack build artifact.
      artifactid:
        type: string
        required: true
        description: The artifact ID of the workflow that uploaded the wasm-webpack build artifact.
  workflow_call:
    inputs:
      runid:
        type: string
        required: true
        description: The run ID of the workflow that uploaded the wasm-webpack build artifact.
      artifactid:
        type: string
        required: true
        description: The artifact ID of the workflow that uploaded the wasm-webpack build artifact.

defaults:
  run:
    working-directory: ./web-ui

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   if: ${{ github.event.workflow_run.conclusion == 'success' }}
  #   steps:

  debug:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
      - uses: actions/download-artifact@v5
        with:
          artifact-ids: ${{ github.event.inputs.artifactid }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Coverage
        run: |
          echo "Run ID: ${{ github.event.inputs.runid }}"
          echo "Artifact ID: ${{ github.event.inputs.artifactid }}"

  coverage:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
      - uses: actions/download-artifact@v5
        with:
          artifact-ids: ${{ github.event.inputs.artifactid }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Coverage
        run: |
          npm ci
          CI=true npm test -- --coverage

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
      - name: Format
        run: |
          npm ci
          npm run format

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
      - name: Lint
        run: |
          npm ci
          npm run lint

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Audit
        run: |
          npm ci
          npm audit --audit-level=critical --production

  outdated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Outdated
        run: |
          npm ci
          npm outdated
    
  publish:
    needs: [coverage]
    # if: github.refs == 'refs/heads/main'
    # if: startsWith(github.event.ref, 'refs/tags/v')
    uses: './.github/workflows/cd-web.yml'
    # with:
    #   environment: prod
