name: CI/CD

on:
  push:
    # branches: ['main']
  pull_request:
    # branches: ['main']
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  ci_rs:
    uses: './.github/workflows/ci-rs.yml'

  ci_js:
    uses: './.github/workflows/ci-js.yml'

  ci_web:
    needs: [ci_js]
    permissions:
      contents: read
      actions: read # for downloading artifacts
    uses: './.github/workflows/ci-web.yml'
    with:
      artifactid: ${{ needs.ci_js.outputs.artifact-id }}

  cd_rs:
    needs: [ci_rs, ci_js, ci_web]
    permissions:
      contents: read
      actions: read # for downloading artifacts
      id-token: write
    # if: github.ref == 'refs/heads/main'
    if: startsWith(github.ref, 'refs/tags/v')
    # if: ${{ (github.ref == 'refs/heads/main') || startsWith(github.ref, 'refs/tags/v') }}
    uses: './.github/workflows/cd-rs.yml'
    with:
      artifactid: ${{ needs.ci_rs.outputs.artifact-id }}
    secrets: inherit # see: https://github.com/actions/runner/issues/1490#issuecomment-1872256710 for why this is required

  cd_js:
    needs: [ci_rs, ci_js, ci_web]
    permissions:
      contents: read
      actions: read # for downloading artifacts
      id-token: write
    # if: github.ref == 'refs/heads/main'
    if: startsWith(github.ref, 'refs/tags/v')
    # if: ${{ (github.ref == 'refs/heads/main') || startsWith(github.ref, 'refs/tags/v') }}
    uses: './.github/workflows/cd-js.yml'
    with:
      artifactid: ${{ needs.ci_js.outputs.artifact-id }}
      artifactid-nodejs: ${{ needs.ci_js.outputs.artifact-id-nodejs }}
    secrets: inherit # see: https://github.com/actions/runner/issues/1490#issuecomment-1872256710 for why this is required

  cd_web:
    needs: [ci_rs, ci_js, ci_web]
    permissions:
      contents: read
      actions: read
      pages: write
      id-token: write
    if: ${{ (github.ref == 'refs/heads/main') || startsWith(github.ref, 'refs/tags/v') }}
    # if: startsWith(github.event.ref, 'refs/tags/v')
    uses: './.github/workflows/cd-web.yml'
    with:
      artifactid: ${{ needs.ci_web.outputs.artifact-id }}
    secrets: inherit # see: https://github.com/actions/runner/issues/1490#issuecomment-1872256710 for why this is required
