name: CI/CD

on:
  push:
    # branches: ['main']
  pull_request:
    # branches: ['main']

env:
  CARGO_TERM_COLOR: always

jobs:
  ci_rs:
    uses: './.github/workflows/ci-rs.yml'

  ci_js:
    uses: './.github/workflows/ci-js.yml'

  ci_web:
    needs: [ci_js]
    permissions: read-all
    uses: './.github/workflows/ci-web.yml'
    with:
      artifactid: ${{ needs.ci_js.outputs.artifact-id }}

  cd_rs:
    needs: [ci_rs, ci_js, ci_web]
    permissions: read-all
    # if: github.refs == 'refs/heads/main'
    # if: startsWith(github.event.ref, 'refs/tags/v')
    uses: './.github/workflows/cd-rs.yml'
    with:
      artifactid: ${{ needs.ci_rs.outputs.artifact-id }}
    # with:
    #   environment: prod

  cd_js:
    needs: [ci_rs, ci_js, ci_web]
    permissions: read-all
    # if: github.refs == 'refs/heads/main'
    # if: startsWith(github.event.ref, 'refs/tags/v')
    uses: './.github/workflows/cd-js.yml'
    with:
      artifactid: ${{ needs.ci_js.outputs.artifact-id }}
    # with:
    #   environment: prod

  cd_web:
    needs: [ci_rs, ci_js, ci_web]
    permissions: read-all
    # if: github.refs == 'refs/heads/main'
    # if: startsWith(github.event.ref, 'refs/tags/v')
    uses: './.github/workflows/cd-web.yml'
    with:
      artifactid: ${{ needs.ci_web.outputs.artifact-id }}
    # with:
    #   environment: prod

  # debug:
  #   runs-on: ubuntu-latest
  #   needs: [ci_web]
  #   permissions: read-all
  #   steps:
  #     - uses: actions/checkout@v5
  #     - name: Debug1
  #       env:
  #         ART_ID: ${{ needs.ci_web.outputs.artifact_id }}
  #         PAGE_URL: ${{ needs.ci_web.outputs.page_url }}
  #       run: |
  #         echo "Artifact ID from previous job is $ART_ID"
  #         echo "Page URL from previous job is $PAGE_URL"
  #     - name: Debug2
  #       run: |
  #         echo 'Run ID is ${{ github.run_id }}'
  #         echo 'Artifact ID is ${{ needs.ci_web.outputs.artifact_id }}'
  #         echo 'Page URL is ${{ needs.ci_web.outputs.page_url }}'
